[package]
name = "RSearch"
version = "0.1.0"
edition = "2021"

[dependencies]
winsafe = "0.0.22"
rayon = "1.5"
egui = "0.30.0" 
eframe = "0.30.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"